name: jaewoo_test
on: [push, fork]
jobs:
  my_second_job:
    name: My second job
    steps:
      - uses: actions/checkout@v2
      - name: Set up env
        uses: actions/setup@v1
        with:
          python-version: 3.9.13
      - name: Install Dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
